In [101]:
import torch
print(torch.__version__)

2.9.0+cu128


Creating tensors


In [102]:
# empty tensors - torch.empty() creates tensors of given shape and allocates memory without filling values
# torch.empty() is used to initialise values

In [103]:
t=torch.empty(2,3)
t # it allocates memory

tensor([[ 2.6955e-19,  4.4913e-41,  1.9929e-29],
        [ 0.0000e+00, -2.7595e+24,  4.4910e-41]])

In [104]:
#check type
type(t)

torch.Tensor

In [105]:
# using zeros - creates a tensor and initialises with zeroes
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [106]:
# torch.ones() - initialises with ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [107]:
torch.rand(2,3) # creates a tensor and fills values randomly between 0 and 1

tensor([[0.6938, 0.7529, 0.6873],
        [0.0716, 0.9869, 0.4623]])

In [108]:
torch.rand(2,3)

tensor([[0.0241, 0.4247, 0.8266],
        [0.7303, 0.4947, 0.8525]])

In [109]:
# use of manual_seed() - without seed, torch.rand() values does'nt repeat but with use of torch.manual_rand() values gets repeated
torch.manual_seed(2)
torch.rand(2,2)

tensor([[0.6147, 0.3810],
        [0.6371, 0.4745]])

In [110]:
torch.manual_seed(2)  # torch.manual_seed(n) -- fix randomness with n, n can be any number
torch.rand(2,2)

tensor([[0.6147, 0.3810],
        [0.6371, 0.4745]])

In [111]:
# using tensor
torch.tensor(([1,2,3],[5,6,7]))

tensor([[1, 2, 3],
        [5, 6, 7]])

In [112]:
# using arange
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [113]:
# using linspace: finds equslly distant points between start and stop values along with required number of values
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [114]:
# torch.eye(n) - used to create a tensor of identity matrix of order n
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

TENSOR SHAPES

In [115]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [116]:
x.shape

torch.Size([2, 3])

In [117]:
# to create a tensor with similar shape of other tensor use _like
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 1, 0]])

In [118]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [119]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [120]:
torch.rand_like(x,dtype=float)

tensor([[0.7088, 0.5403, 0.9133],
        [0.5257, 0.1204, 0.2669]], dtype=torch.float64)

TENOR DATA TYPES

In [121]:
# dtype - used to find data type
x.dtype

torch.int64

In [122]:
#assign data type
y=torch.tensor([1.0,2.0,3.0],dtype=int)
y

tensor([1, 2, 3])

In [123]:
# .to() - to change a tensor data type
x.to(torch.int16)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int16)

Mathematical Operations on tensors

In [124]:
# with scalars
x=torch.rand(2,2)
x

tensor([[0.7116, 0.2050],
        [0.3078, 0.9809]])

In [125]:
x+2

tensor([[2.7116, 2.2050],
        [2.3078, 2.9809]])

In [126]:
x-2

tensor([[-1.2884, -1.7950],
        [-1.6922, -1.0191]])

In [127]:
x*2

tensor([[1.4232, 0.4101],
        [0.6156, 1.9617]])

In [128]:
x/2

tensor([[0.3558, 0.1025],
        [0.1539, 0.4904]])

In [129]:
(x*100)%2

tensor([[1.1597, 0.5034],
        [0.7783, 0.0859]])

In [130]:
x**2

tensor([[0.5064, 0.0420],
        [0.0947, 0.9621]])

In [131]:
a=torch.rand(2,3)
b=torch.rand(2,3)
print(a)
print(b)

tensor([[0.0103, 0.4660, 0.4604],
        [0.8547, 0.4525, 0.6317]])
tensor([[0.4760, 0.2200, 0.2166],
        [0.2571, 0.0458, 0.1755]])


In [132]:
a+b

tensor([[0.4863, 0.6861, 0.6770],
        [1.1117, 0.4983, 0.8072]])

In [133]:
a-b

tensor([[-0.4657,  0.2460,  0.2438],
        [ 0.5976,  0.4067,  0.4562]])

In [134]:
a*b

tensor([[0.0049, 0.1025, 0.0997],
        [0.2197, 0.0207, 0.1109]])

In [135]:
a/b

tensor([[0.0216, 2.1181, 2.1254],
        [3.3244, 9.8796, 3.5990]])

In [136]:
a%b

tensor([[0.0103, 0.0260, 0.0272],
        [0.0834, 0.0403, 0.1051]])

In [137]:
c=torch.tensor([1,-3,5,-6.78])
c

tensor([ 1.0000, -3.0000,  5.0000, -6.7800])

In [138]:
# .abs() - mod
torch.abs(c)

tensor([1.0000, 3.0000, 5.0000, 6.7800])

In [139]:
# .neg() - acts like negation
c.neg()

tensor([-1.0000,  3.0000, -5.0000,  6.7800])

In [140]:
torch.round(c)

tensor([ 1., -3.,  5., -7.])

In [141]:
# clamp - used to limit the values between range
torch.clamp(c,min=2,max=5)

tensor([2., 2., 5., 2.])

In [142]:
e=torch.randint(size=(2,3),low=0,high=10,dtype=float) # low, high defines range where low is inclusive and high is exclusive
e

tensor([[6., 1., 6.],
        [0., 9., 1.]], dtype=torch.float64)

In [143]:
# sum()
torch.sum(e)

tensor(23., dtype=torch.float64)

In [144]:
# along with rows and columns, for rows dimensions=1, columns = 0
torch.sum(e,dim=1)

tensor([13., 10.], dtype=torch.float64)

In [145]:
torch.sum(e,dim=0)

tensor([ 6., 10.,  7.], dtype=torch.float64)

In [146]:
torch.mean(e)

tensor(3.8333, dtype=torch.float64)

In [147]:
# along columns
torch.mean(e,dim=0)

tensor([3.0000, 5.0000, 3.5000], dtype=torch.float64)

In [148]:
torch.median(e)

tensor(1., dtype=torch.float64)

In [149]:
torch.min(e)
torch.max(e)

tensor(9., dtype=torch.float64)

In [150]:
torch.prod(e)

tensor(0., dtype=torch.float64)

In [151]:
torch.var(e)

tensor(13.3667, dtype=torch.float64)

In [152]:
torch.std(e)

tensor(3.6560, dtype=torch.float64)

In [153]:
# argmax - tells the position of biggest item
torch.argmax(e)

tensor(4)

In [154]:
# argmin - tells position of smallest item
torch.argmin(e)

tensor(3)

MATRIX OPERATIONS

In [155]:
g=torch.randint(size=(2,3),low=0,high=10)
f=torch.randint(size=(3,2),low=0,high=10)
print(g)
print(f)

tensor([[3, 0, 8],
        [2, 8, 7]])
tensor([[1, 1],
        [1, 2],
        [0, 8]])


In [156]:
# Matrix multiplication
torch.matmul(g,f)

tensor([[ 3, 67],
        [10, 74]])

In [157]:
# dot product - dot
v1 = torch.tensor([1,2])
v2=torch.tensor([3,4])
torch.dot(v1,v2)

tensor(11)

In [158]:
f

tensor([[1, 1],
        [1, 2],
        [0, 8]])

In [159]:
# transpose - inverting rows to columns and columns to rows
torch.transpose(f,0,1) # 0 and 1 are dimension i.e we're swapping rows with columns and vice versa

tensor([[1, 1, 0],
        [1, 2, 8]])

In [160]:
f.T

tensor([[1, 1, 0],
        [1, 2, 8]])

In [161]:
# determinant
torch.det(torch.rand(3,3)*10)

tensor(70.8840)

In [162]:
torch.inverse(torch.rand(3,3)) # DET and inverse only works if we have a square matrix

tensor([[ 2.4445, -0.1023, -2.6159],
        [-1.8167,  0.0243,  3.5220],
        [ 0.2132,  1.1040, -1.8668]])

In [163]:
torch.log(f)

tensor([[0.0000, 0.0000],
        [0.0000, 0.6931],
        [  -inf, 2.0794]])

In [164]:
torch.exp(f)

tensor([[2.7183e+00, 2.7183e+00],
        [2.7183e+00, 7.3891e+00],
        [1.0000e+00, 2.9810e+03]])

In [165]:
torch.sqrt(f)

tensor([[1.0000, 1.0000],
        [1.0000, 1.4142],
        [0.0000, 2.8284]])

In [166]:
torch.sigmoid(f)

tensor([[0.7311, 0.7311],
        [0.7311, 0.8808],
        [0.5000, 0.9997]])

In [167]:
# softmax - converts given numbers to probabilities with sum=1
# converts x to exp(x) : softmax(x) = np.exp(x)/np.sum(np.exp(x))
torch.softmax(x,0)

tensor([[0.5996, 0.3152],
        [0.4004, 0.6848]])

In [168]:
# relu - rectified linear unit : relu(x) = max(0,x) if x>0 relu(x)=x else 0
torch.relu(x)

tensor([[0.7116, 0.2050],
        [0.3078, 0.9809]])

Inplace operations

In [169]:
m = torch.rand(2,3)
n = torch.rand(2,3)
print(m)
print(n)

tensor([[0.3406, 0.7438, 0.0445],
        [0.9356, 0.1712, 0.6581]])
tensor([[0.4811, 0.5881, 0.5484],
        [0.0326, 0.3926, 0.1839]])


In [170]:
m+n # a new tensor is being created and memory is allocated, in working with real dataset with large size too space consuming

tensor([[0.8217, 1.3319, 0.5930],
        [0.9682, 0.5638, 0.8421]])

In [171]:
m.add_(n) # add_() - new tensor sum is being stored in m

tensor([[0.8217, 1.3319, 0.5930],
        [0.9682, 0.5638, 0.8421]])

In [172]:
m

tensor([[0.8217, 1.3319, 0.5930],
        [0.9682, 0.5638, 0.8421]])

In [173]:
# irrespective of function, at the end use _ so that instead of allocating memory to a new tensor it uses the old one
# inplace operator

In [174]:
# copying a tensor - instead of using a assignment operator = which leads to allocation of same memory space better to use .clone()

In [175]:
a=torch.rand(2,3)
a

tensor([[0.9251, 0.4386, 0.0021],
        [0.6211, 0.7171, 0.2762]])

In [176]:
b=a.clone()
b # here memory location of a and b differs

tensor([[0.9251, 0.4386, 0.0021],
        [0.6211, 0.7171, 0.2762]])

In [177]:
id(a)

137653301466352

In [178]:
id(b)

137653301474112

Tensor operations on GPU

In [179]:
torch.cuda.is_available()

True

In [180]:
d=torch.device("cuda") # this tells pytorch to use device cuda
d

device(type='cuda')

In [181]:
# creating a tensor on gpu
torch.tensor([1,2,3],device=d)

tensor([1, 2, 3], device='cuda:0')

In [182]:
torch.rand((2,3),device=d)

tensor([[0.4254, 0.8305, 0.3370],
        [0.6842, 0.5668, 0.6650]], device='cuda:0')

In [183]:
# moving a tensor from cpu to gpu, use .to()
b=a.to(d)
b

tensor([[0.9251, 0.4386, 0.0021],
        [0.6211, 0.7171, 0.2762]], device='cuda:0')

In [184]:
b+5 # whatever operations we perform, they work on gpu and faster compared to a tensor created on cpu

tensor([[5.9251, 5.4386, 5.0021],
        [5.6211, 5.7171, 5.2762]], device='cuda:0')

In [185]:
# Reshaping tensors
a= torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [186]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [187]:
# flatten - brings back tensor to 1D, converts a given tensor to a vector
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [188]:
# permute - switches the shape between dimensions
b=torch.rand(2,3,4)
b

tensor([[[0.4531, 0.7162, 0.1889, 0.2357],
         [0.4518, 0.1489, 0.8073, 0.5409],
         [0.7992, 0.7677, 0.1147, 0.1884]],

        [[0.1580, 0.3393, 0.3173, 0.4194],
         [0.0163, 0.7111, 0.7837, 0.6585],
         [0.8177, 0.8756, 0.0064, 0.5755]]])

In [189]:
b.permute(2,1,0).shape # it switches the given dimensions such that columns dim =4,3,2

torch.Size([4, 3, 2])

In [190]:
b.permute(2,1,0)

tensor([[[0.4531, 0.1580],
         [0.4518, 0.0163],
         [0.7992, 0.8177]],

        [[0.7162, 0.3393],
         [0.1489, 0.7111],
         [0.7677, 0.8756]],

        [[0.1889, 0.3173],
         [0.8073, 0.7837],
         [0.1147, 0.0064]],

        [[0.2357, 0.4194],
         [0.5409, 0.6585],
         [0.1884, 0.5755]]])

In [191]:
import numpy as np
import torch

In [191]:
# conversion of numpy array to pytorch tensor and vice versa

In [194]:
a = torch.rand(2,3)
a

tensor([[0.4261, 0.9455, 0.4686],
        [0.7711, 0.8661, 0.7228]])

In [195]:
a.numpy()

array([[0.42611468, 0.94548553, 0.46856058],
       [0.771136  , 0.86613774, 0.72276145]], dtype=float32)

In [197]:
c=np.array([1,2,3,4])
c

array([1, 2, 3, 4])

In [198]:
torch.from_numpy(c)

tensor([1, 2, 3, 4])